-- ⚠️  DEPRECATED — This file is kept only for reference.
-- Use supabase/migrations/20260717190000_secure_platform.sql instead.
-- The migration has the correct RLS policies using 'app_metadata.is_admin'.
