alter table public.release_radar_items
  alter column image_url drop not null;

alter table public.release_radar_items
  drop constraint if exists release_radar_items_image_url_check;

alter table public.release_radar_items
  add constraint release_radar_items_image_url_check
  check (image_url is null or image_url ~ '^https://');

with catalog(id, game, release_label, release_date, platforms) as (
  values
    ('heartopia', 'Heartopia', '7 de Janeiro', date '2026-01-07', array['PC','IOS','ANDROID']),
    ('blasten', 'Blasten!!', '8 de Janeiro', date '2026-01-08', array['PC']),
    ('cozy-caravan', 'Cozy Caravan', '8 de Janeiro', date '2026-01-08', array['PC']),
    ('pathologic-3', 'Pathologic 3', '9 de Janeiro', date '2026-01-09', array['PC']),
    ('spear', 'Spear', '9 de Janeiro', date '2026-01-09', array['XSX']),
    ('quarantine-zone-the-last-check', 'Quarantine Zone: The Last Check', '12 de Janeiro', date '2026-01-12', array['PC']),
    ('streetdog-bmx', 'Streetdog BMX', '14 de Janeiro', date '2026-01-14', array['PC']),
    ('cassette-boy', 'Cassette Boy', '15 de Janeiro', date '2026-01-15', array['PC','SWITCH','PS5','PS4','XSX','XBOX ONE']),
    ('trails-beyond-the-horizon', 'The Legend of Heroes: Trails Beyond the Horizon', '15 de Janeiro', date '2026-01-15', array['PS5','PS4','SWITCH 2','SWITCH','PC']),
    ('brokenlore-unfollow', 'BrokenLore: Unfollow', '16 de Janeiro', date '2026-01-16', array['PS5','XSX','PC']),
    ('ghetto-zombies-graffiti-squad', 'Ghetto Zombies Graffiti Squad', '16 de Janeiro', date '2026-01-16', array['PC']),
    ('carnedge', 'Carnedge', '19 de Janeiro', date '2026-01-19', array['PC']),
    ('duet-night-abyss', 'Duet Night Abyss', '19 de Janeiro', date '2026-01-19', array['PC']),
    ('mio-memories-in-orbit', 'MIO: Memories In Orbit', '20 de Janeiro', date '2026-01-20', array['XSX','PS5','SWITCH 2','SWITCH','PC']),
    ('eldegarde', 'Eldegarde', '21 de Janeiro', date '2026-01-21', array['PC']),
    ('gooey', 'Gooey', '21 de Janeiro', date '2026-01-21', array['PC']),
    ('tr-49', 'TR-49', '21 de Janeiro', date '2026-01-21', array['PC','IOS']),
    ('arknights-endfield', 'Arknights: Endfield', '22 de Janeiro', date '2026-01-22', array['PS5','PC','IOS','ANDROID']),
    ('hermit-and-pig', 'Hermit and Pig', '22 de Janeiro', date '2026-01-22', array['PC']),
    ('banquet-for-fools', 'Banquet For Fools', '23 de Janeiro', date '2026-01-23', array['PC']),
    ('escape-the-ever-after', 'Escape The Ever After', '23 de Janeiro', date '2026-01-23', array['PS5','XSX','SWITCH','PC']),
    ('the-fortress', 'The Fortress', '23 de Janeiro', date '2026-01-23', array['PC']),
    ('highguard', 'Highguard', '26 de Janeiro', date '2026-01-26', array['PS5','XSX','PC']),
    ('conquest-tactics', 'Conquest Tactics', '27 de Janeiro', date '2026-01-27', array['PC']),
    ('earth-must-die', 'Earth Must Die', '27 de Janeiro', date '2026-01-27', array['PC']),
    ('rightfully-beary-arms', 'Rightfully, Beary Arms', '27 de Janeiro', date '2026-01-27', array['XSX','PC']),
    ('underground-garage', 'Underground Garage', '27 de Janeiro', date '2026-01-27', array['PC']),
    ('lanesplit', 'Lanesplit', '28 de Janeiro', date '2026-01-28', array['PC']),
    ('seven-deadly-sins-origin', 'The Seven Deadly Sins: Origin', '28 de Janeiro', date '2026-01-28', array['PS5','PC','IOS','ANDROID']),
    ('cairn', 'Cairn', '29 de Janeiro', date '2026-01-29', array['PS5','PC']),
    ('dark-auction', 'Dark Auction', '29 de Janeiro', date '2026-01-29', array['PS5','SWITCH','PC']),
    ('i-hate-this-place', 'I Hate This Place', '29 de Janeiro', date '2026-01-29', array['PS5','XSX','SWITCH','PC']),
    ('space-warlord-baby-trading-simulator', 'Space Warlord Baby Trading Simulator', '29 de Janeiro', date '2026-01-29', array['PC']),
    ('ufophilia', 'Ufophilia', '29 de Janeiro', date '2026-01-29', array['PS5','PC']),
    ('code-vein-2', 'Code Vein 2', '30 de Janeiro', date '2026-01-30', array['PS5','XSX','PC']),
    ('folklore-hunter', 'Folklore Hunter', '30 de Janeiro', date '2026-01-30', array['PC']),
    ('my-tiny-garden', 'My Tiny Garden', '30 de Janeiro', date '2026-01-30', array['PC']),
    ('occupy-mars-the-game', 'Occupy Mars: The Game', '30 de Janeiro', date '2026-01-30', array['PC']),
    ('the-18th-attic', 'The 18th Attic', '2 de Fevereiro', date '2026-02-02', array['PC']),
    ('crimson-capes', 'Crimson Capes', '3 de Fevereiro', date '2026-02-03', array['PC']),
    ('dragon-quest-vii-reimagined', 'Dragon Quest VII Reimagined', '5 de Fevereiro', date '2026-02-05', array['PS5','XSX','SWITCH 2','SWITCH','PC']),
    ('unemployment-simulator-2018', 'Unemployment Simulator 2018', '5 de Fevereiro', date '2026-02-05', array['PC']),
    ('dead-pets', 'Dead Pets: A Punk Rock Slice Of Life Sim', '6 de Fevereiro', date '2026-02-06', array['PC']),
    ('ghost-gunners', 'Ghost Gunners', '6 de Fevereiro', date '2026-02-06', array['PC']),
    ('humanityz', 'HumanityZ', '6 de Fevereiro', date '2026-02-06', array['PC']),
    ('my-hero-academia-alls-justice', 'My Hero Academia: All''s Justice', '6 de Fevereiro', date '2026-02-06', array['PS5','XSX','PC']),
    ('nioh-3', 'Nioh 3', '6 de Fevereiro', date '2026-02-06', array['PS5']),
    ('mewgenics', 'Mewgenics', '10 de Fevereiro', date '2026-02-10', array['PC']),
    ('relooted', 'Relooted', '10 de Fevereiro', date '2026-02-10', array['PC']),
    ('the-prisoning-fletchers-quest', 'The Prisoning: Fletcher''s Quest', '10 de Fevereiro', date '2026-02-10', array['SWITCH','PC']),
    ('romeo-is-a-dead-man', 'Romeo is a Dead Man', '11 de Fevereiro', date '2026-02-11', array['PS5','XSX','PC']),
    ('blazblue-entropy-effect-x', 'BlazBlue Entropy Effect X', '12 de Fevereiro', date '2026-02-12', array['PS5','XSX','SWITCH']),
    ('disciples-domination', 'Disciples: Domination', '12 de Fevereiro', date '2026-02-12', array['PC']),
    ('mario-tennis-fever', 'Mario Tennis Fever', '12 de Fevereiro', date '2026-02-12', array['SWITCH 2']),
    ('ride-6', 'Ride 6', '12 de Fevereiro', date '2026-02-12', array['PS5','XSX','PC']),
    ('clue-murder-by-death', 'Clue: Murder by Death', '13 de Fevereiro', date '2026-02-13', array['PS5','PS4','XSX','XBOX ONE']),
    ('high-on-life-2', 'High on Life 2', '13 de Fevereiro', date '2026-02-13', array['PS5','XSX','PC']),
    ('reanimal', 'Reanimal', '13 de Fevereiro', date '2026-02-13', array['PS5','XSX','SWITCH 2','PC']),
    ('dobbel-dungeon', 'Dobbel Dungeon', '16 de Fevereiro', date '2026-02-16', array['PC']),
    ('menherarium', 'Menherarium', '18 de Fevereiro', date '2026-02-18', array['PC']),
    ('strange-brew', 'Strange Brew', '18 de Fevereiro', date '2026-02-18', array['PC']),
    ('the-killing-stone', 'The Killing Stone', '18 de Fevereiro', date '2026-02-18', array['PC']),
    ('demon-tides', 'Demon Tides', '19 de Fevereiro', date '2026-02-19', array['PC']),
    ('love-eternal', 'Love Eternal', '19 de Fevereiro', date '2026-02-19', array['PS5','PS4','XSX','SWITCH','PC']),
    ('styx-blades-of-greed', 'Styx: Blades of Greed', '19 de Fevereiro', date '2026-02-19', array['PS5','XSX','PC']),
    ('ys-x-proud-nordics', 'Ys X: Proud Nordics', '20 de Fevereiro', date '2026-02-20', array['PS5','SWITCH 2','PC']),
    ('rainbow-six-mobile', 'Rainbow Six Mobile', '23 de Fevereiro', date '2026-02-23', array['IOS','ANDROID']),
    ('tides-of-tomorrow', 'Tides of Tomorrow', '24 de Fevereiro', date '2026-02-24', array['PS5','XSX','PC']),
    ('reigns-the-witcher', 'Reigns: The Witcher', '25 de Fevereiro', date '2026-02-25', array['PC','IOS','ANDROID']),
    ('tales-of-berseria-remastered', 'Tales of Berseria Remastered', '26 de Fevereiro', date '2026-02-26', array['PS5','XSX','SWITCH','PC']),
    ('resident-evil-requiem', 'Resident Evil Requiem', '27 de Fevereiro', date '2026-02-27', array['PS5','XSX','SWITCH 2','PC']),
    ('gnaughty-gnomes', 'Gnaughty Gnomes', '3 de Março', date '2026-03-03', array['PC']),
    ('scott-pilgrim-ex', 'Scott Pilgrim EX', '3 de Março', date '2026-03-03', array['PS5','PS4','XSX','SWITCH','PC']),
    ('homura-hime', 'Homura Hime', '4 de Março', date '2026-03-04', array['PC']),
    ('marathon', 'Marathon', '5 de Março', date '2026-03-05', array['PS5','XSX','PC']),
    ('never-grace', 'Never Grace: The Witch and the Curse', '5 de Março', date '2026-03-05', array['PS5','PS4','XSX','XBOX ONE','SWITCH','PC']),
    ('lost-and-found-co', 'Lost and Found Co.', '6 de Março', date '2026-03-06', array['PC']),
    ('1348-ex-voto', '1348 Ex Voto', '12 de Março', date '2026-03-12', array['PS5','PC']),
    ('fatal-frame-ii-remake', 'Fatal Frame II: Crimson Butterfly Remake', '12 de Março', date '2026-03-12', array['PS5','XSX','SWITCH 2','PC']),
    ('monster-hunter-stories-3', 'Monster Hunter Stories 3: Twisted Reflection', '13 de Março', date '2026-03-13', array['PS5','XSX','SWITCH 2','PC']),
    ('mlb-the-show-26', 'MLB The Show 26', '17 de Março', date '2026-03-17', array['PS5','XSX','SWITCH']),
    ('xploit-zero', 'Xploit.zero', '17 de Março', date '2026-03-17', array['QUEST 3']),
    ('crimson-desert', 'Crimson Desert', '19 de Março', date '2026-03-19', array['PS5','XSX','PC']),
    ('dynasty-warriors-3-remastered', 'Dynasty Warriors 3: Complete Edition Remastered', '19 de Março', date '2026-03-19', array['PS5','XSX','SWITCH 2','SWITCH','PC']),
    ('mouse-pi-for-hire', 'Mouse: P.I. For Hire', '19 de Março', date '2026-03-19', array['PS5','PS4','XSX','XBOX ONE','SWITCH','PC']),
    ('ghost-master-resurrection', 'Ghost Master: Resurrection', '20 de Março', date '2026-03-20', array['PS5','XSX','SWITCH','PC']),
    ('rubato', 'Rubato', '20 de Março', date '2026-03-20', array['PS5','SWITCH','PC']),
    ('ariana-and-the-elder-codex', 'Ariana and the Elder Codex', '24 de Março', date '2026-03-24', array['PS5','PS4','SWITCH']),
    ('copa-city', 'Copa City', '26 de Março', date '2026-03-26', array['PS5','XSX','XBOX ONE','PC']),
    ('life-is-strange-reunion', 'Life is Strange: Reunion', '26 de Março', date '2026-03-26', array['PS5','XSX','PC']),
    ('screamer', 'Screamer', '26 de Março', date '2026-03-26', array['PS5','XSX','PC']),
    ('pokemon-champions', 'Pokémon Champions', '8 de Abril', date '2026-04-08', array['SWITCH 2','SWITCH','ANDROID','IOS']),
    ('before-i-go', 'Before I Go', '13 de Abril', date '2026-04-13', array['PS5','XSX','XBOX ONE','SWITCH','PC']),
    ('shantytown', 'ShantyTown', '16 de Abril', date '2026-04-16', array['PC']),
    ('tomodachi-life-living-the-dream', 'Tomodachi Life: Living the Dream', '16 de Abril', date '2026-04-16', array['SWITCH']),
    ('pragmata', 'Pragmata', '24 de Abril', date '2026-04-24', array['PS5','XSX','PC']),
    ('aphelion', 'Aphelion', '28 de Abril', date '2026-04-28', array['PS5','XSX','PC']),
    ('diablo-iv-lord-of-hatred', 'Diablo IV: Lord of Hatred', '28 de Abril', date '2026-04-28', array['PS5','PS4','XSX','XBOX ONE','PC']),
    ('invincible-vs', 'Invincible Vs.', '30 de Abril', date '2026-04-30', array['PS5','XSX','PC']),
    ('saros', 'Saros', '30 de Abril', date '2026-04-30', array['PS5']),
    ('dead-as-disco', 'Dead as Disco', '5 de Maio', date '2026-05-05', array['PS5','XSX','SWITCH','SWITCH 2','PC']),
    ('mixtape', 'Mixtape', '7 de Maio', date '2026-05-07', array['PS5','XSX','SWITCH 2','PC']),
    ('outbound', 'Outbound', '11 de Maio', date '2026-05-11', array['PS5','XSX','XBOX ONE','SWITCH','SWITCH 2','PC']),
    ('battlestar-galactica-scattered-hopes', 'Battlestar Galactica: Scattered Hopes', '11 de Maio', date '2026-05-11', array['PC']),
    ('call-of-the-elder-gods', 'Call of the Elder Gods', '12 de Maio', date '2026-05-12', array['PS5','XSX','SWITCH 2','PC']),
    ('directive-8020', 'Directive 8020', '12 de Maio', date '2026-05-12', array['PS5','XSX','PC']),
    ('subnautica-2', 'Subnautica 2', '14 de Maio', date '2026-05-14', array['XSX','PC']),
    ('corsairs-battle-of-the-caribbean', 'Corsairs: Battle of the Caribbean', '18 de Maio', date '2026-05-18', array['PC']),
    ('farming-simulator-26-switch-edition', 'Farming Simulator 26: Nintendo Switch Edition', '19 de Maio', date '2026-05-19', array['SWITCH','SWITCH 2']),
    ('forza-horizon-6', 'Forza Horizon 6', '19 de Maio', date '2026-05-19', array['PS5','XSX','PC']),
    ('thick-as-thieves', 'Thick as Thieves', '20 de Maio', date '2026-05-20', array['PS5','XSX','PC']),
    ('yoshi-and-the-mysterious-book', 'Yoshi and the Mysterious Book', '21 de Maio', date '2026-05-21', array['SWITCH 2']),
    ('bubsy-4d', 'Bubsy 4D', '22 de Maio', date '2026-05-22', array['PS5','PS4','XSX','XBOX ONE','SWITCH 2','SWITCH','PC']),
    ('enter-the-chronosphere', 'Enter the Chronosphere', '25 de Maio', date '2026-05-25', array['PC']),
    ('paralives', 'Paralives', '25 de Maio', date '2026-05-25', array['PC']),
    ('realm-of-ink', 'Realm of Ink', '26 de Maio', date '2026-05-26', array['PS5','XSX','SWITCH','PC']),
    ('lumentale-memories-of-trey', 'LumenTale: Memories of Trey', '26 de Maio', date '2026-05-26', array['SWITCH','PC']),
    ('yerba-buena', 'Yerba Buena', '26 de Maio', date '2026-05-26', array['PS5','XSX','PC']),
    ('stonemachia', 'Stonemachia', '26 de Maio', date '2026-05-26', array['PC']),
    ('007-first-light', '007 First Light', '27 de Maio', date '2026-05-27', array['PS5','XSX','SWITCH 2','PC']),
    ('echo-generation-2', 'Echo Generation 2', '27 de Maio', date '2026-05-27', array['XSX','PC']),
    ('schrodingers-call', 'Schrödinger''s Call', '27 de Maio', date '2026-05-27', array['SWITCH','PC']),
    ('crashout-crew', 'Crashout Crew', '28 de Maio', date '2026-05-28', array['XSX','PC']),
    ('moonsigil-atlas', 'Moonsigil Atlas', '28 de Maio', date '2026-05-28', array['PC']),
    ('pictonico', 'Pictonico!', '28 de Maio', date '2026-05-28', array['ANDROID','IOS']),
    ('lego-batman-legacy-of-the-dark-knight', 'LEGO Batman: Legacy of the Dark Knight', '29 de Maio', date '2026-05-29', array['PS5','XSX','SWITCH 2','PC']),
    ('efootball-kick-off', 'eFootball Kick-Off!', '3 de Junho', date '2026-06-03', array['SWITCH 2']),
    ('killer-bean', 'Killer Bean', '8 de Junho', date '2026-06-08', array['PC']),
    ('nba-the-run', 'NBA The Run', '9 de Junho', date '2026-06-09', array['PS5','XSX','PC']),
    ('rf-online-next', 'RF Online Next', '15 de Junho', date '2026-06-15', array['PC','IOS','ANDROID']),
    ('barbie-horse-ride-and-rescue', 'Barbie: Horse Ride & Rescue', '16 de Junho', date '2026-06-16', array['SWITCH 2','ANDROID','PC','IOS']),
    ('adventures-of-elliot', 'The Adventures of Elliot: The Millennium Tales', '18 de Junho', date '2026-06-18', array['PS5','XSX','SWITCH 2','PC']),
    ('dark-scrolls', 'Dark Scrolls', '22 de Junho', date '2026-06-22', array['SWITCH','PC']),
    ('star-fox', 'Star Fox', '25 de Junho', date '2026-06-25', array['SWITCH 2']),
    ('phantom-blade-zero', 'Phantom Blade Zero', '9 de Setembro', date '2026-09-09', array['PS5','PC']),
    ('bus-simulator-27', 'Bus Simulator 27', '8 de Setembro', date '2026-09-08', array['PS5','XSX','PC']),
    ('grand-theft-auto-vi', 'Grand Theft Auto VI', '19 de Novembro', date '2026-11-19', array['PS5','XSX'])
)
insert into public.release_radar_items
  (id, game, release_label, release_date, schedule_label, platforms, image_url, badge, category, sort_order)
select
  id,
  game,
  release_label,
  release_date,
  'Data confirmada',
  platforms,
  null,
  'Lançamento',
  'upcoming',
  1000 + row_number() over (order by release_date, game) * 10
from catalog
on conflict (id) do nothing;

with catalog(game) as (
  select unnest(array[
    '1999Tokoyo Building',
    '4Dead',
    'Ace Combat 8: Wings of Theve',
    'Acts of Blood',
    'Aeterna Lucis',
    'Agefield High: Rock The School',
    'Aniimo',
    'A Planet Full of Cats',
    'Armatus',
    'At Fate''s End',
    'Athelan Battlegrounds',
    'Beast of Reincarnation',
    'Bestiario',
    'Bloodstained: The Scarlet Engagement',
    'Bobo Bay',
    'Bolt Action',
    'Carmageddon: Rogue Shift',
    'Celestial Return',
    'Children''s Garden',
    'Clean Up Earth',
    'Control Resonant',
    'CrisisX',
    'Crown of Greed',
    'Cthulhu',
    'Danganronpa 2x2',
    'Danger Mouse',
    'Dark Island: Faded Memories',
    'Decapolice',
    'Denshattack!',
    'Dissidia Duellum Final Fantasy',
    'Dosa Divas: One Last Meal',
    'Dracamar',
    'Edge of Memories',
    'Emberville',
    'End of Abyss',
    'Evil Inside VR',
    'Fable',
    'Fate/Extra Record',
    'Fire Emblem: Fortune''s Weave',
    'Forbidden Solitaire',
    'Foxy Dumplings',
    'FreeStyle Football 2',
    'Gallipoli',
    'Game of Thrones: War for Westeros',
    'Ghost Sector',
    'Gothic 1 Remake',
    'Hack n Stack',
    'Hashire Hebereke: EX',
    'Hela',
    'Hordes of Fate',
    'InZoi',
    'John Carpenter''s Toxic Commando',
    'Kingdom Loop',
    'Kiln',
    'Knights Province',
    'Kusan: City of Wolves',
    'Lifted',
    'Limit Zero Breakers',
    'Little Nemo and the Guardians of Slumberland',
    'Lords of the Fallen 2',
    'Mad King Redemption',
    'Marvel 1943: Rise of Hydra',
    'Marvel Tokon: Fighting Souls',
    'Marvel''s Wolverine',
    'Maseylia: Echoes of the Past',
    'Metro Rivals: New York',
    'Mortal Shell II',
    'Mudang: Two Hearts',
    'Nocturnal 2',
    'No Stone Unturned',
    'No Vacation For An Executioner',
    'Oblitacrater',
    'Onimusha: Way of the Sword',
    'Ontos',
    'Orbitals',
    'Order of the Sinking Star',
    'Otome Daoshi: Fighting for Love',
    'Out of Words',
    'Outward 2',
    'Paranormal Activity',
    'Pearls of Wisdom',
    'Path of Mystery: A Brush With Death',
    'Planet of Lana 2',
    'Port of Jumanah',
    'Prince of Persia: The Sands of Time',
    'PVKK',
    'Quartermaster',
    'Resonance: A Plague Tale Legacy',
    'Road Truckers: New Beginning',
    'SacriFire',
    'Sea of Remnants',
    'Seina: A Tale of Spirits',
    'Shadowman: Darque Legacy',
    'Shadow of the Road',
    'Shipping Store Simulator 2037',
    'Silent Planet: Elegy of a Dying World',
    'Silver Pines',
    'Skate 1.0 version',
    'Slay the Spire 2 early access',
    'Squadron 42',
    'Springs, Eternal',
    'Sprint City',
    'Starship Troopers: Ultimate Bug War',
    'Star Wars: Galactic Racer',
    'Star Wars: Zero Company',
    'Stupid Never Dies',
    'Subnautica 2 early access',
    'Sudden Strike 5',
    'Super Mario Bros. Wonder Nintendo Switch 2 Edition + Meetup in Bellabel Park',
    'Super Meat Boy 3D',
    'The Alighieri Circle: Dante''s Bloodline',
    'The Backworld',
    'The Blood of Dawnwalker',
    'The Dungeon Experience',
    'The Duskbloods',
    'The Mound: Omen of Cthulhu',
    'The Occultist',
    'The Sinking City 2',
    'Titan Quest 2 versão 1.0',
    'Tomb Raider: Legacy of Atlantis',
    'Train Kingdom',
    'Tristia: Chronicles',
    'UnGodly',
    'Valor Mortis',
    'Wabisabi SushiDerby',
    'Warhammer Survivors',
    'Wax Heads',
    'Well Keeper',
    'Witchbrook',
    'Worlds Explorers',
    'WWE 2K26',
    'Ys Memoire: Revelations in Celceta',
    'Yunyun Syndrome!? Rhythm Psychosis',
    'Zero Parades'
  ]::text[])
)
insert into public.release_radar_items
  (id, game, release_label, release_date, schedule_label, platforms, image_url, badge, category, sort_order)
select
  'catalog-' || substr(md5(game), 1, 16),
  game,
  'Sem data definida',
  null,
  'A confirmar',
  array[]::text[],
  null,
  'A confirmar',
  'upcoming',
  7000 + row_number() over (order by game) * 10
from catalog
where not exists (
  select 1
  from public.release_radar_items existing
  where lower(existing.game) = lower(catalog.game)
)
on conflict (id) do nothing;

with catalog(id, game, release_label, release_date, platforms) as (
  values
    ('ganbare-goemon-daishuugou', 'Ganbare Goemon Daishuugou!', '2 de Julho', date '2026-07-02', array['PC','SWITCH','PS5']),
    ('rhythm-heaven-groove', 'Rhythm Heaven Groove', '2 de Julho', date '2026-07-02', array['SWITCH','SWITCH 2']),
    ('ao-oni', 'Ao Oni', '3 de Julho', date '2026-07-03', array['PS5']),
    ('undergrounded', 'Undergrounded', '3 de Julho', date '2026-07-03', array['PC']),
    ('doom-dark-ages-revelations', 'Doom The Dark Ages Revelations', '7 de Julho', date '2026-07-07', array['PC','PS5','XSX']),
    ('moonlight-peaks', 'Moonlight Peaks', '7 de Julho', date '2026-07-07', array['PC','SWITCH','SWITCH 2']),
    ('assassins-creed-black-flag-resynced', 'Assassin''s Creed Black Flag Resynced', '9 de Julho', date '2026-07-09', array['PC','PS5','XSX']),
    ('backyard-baseball', 'Backyard Baseball', '9 de Julho', date '2026-07-09', array['PC','SWITCH','PS5','XSX']),
    ('ea-sports-college-football-27', 'EA Sports College Football 27', '9 de Julho', date '2026-07-09', array['PC','PS5','XSX']),
    ('granblue-fantasy-relink-endless-ragnarok', 'Granblue Fantasy Relink Endless Ragnarok', '9 de Julho', date '2026-07-09', array['PC','SWITCH 2','PS5','PS4']),
    ('gunvolt-chronicles-dual-collection', 'Gunvolt Chronicles Luminous Avenger iX 1+2 Dual Collection', '9 de Julho', date '2026-07-09', array['PC','SWITCH','SWITCH 2','PS5']),
    ('tokyo-valkyries', 'Tokyo Valkyries', '9 de Julho', date '2026-07-09', array['PC','SWITCH']),
    ('digimon-story-time-stranger', 'Digimon Story Time Stranger', '10 de Julho', date '2026-07-10', array['SWITCH','SWITCH 2']),
    ('echoes-of-aincrad', 'Echoes of Aincrad', '10 de Julho', date '2026-07-10', array['PC','PS5','XSX']),
    ('palworld', 'Palworld', '10 de Julho', date '2026-07-10', array['PC','PS5','XSX','XBOX ONE']),
    ('wuthering-waves', 'Wuthering Waves', '10 de Julho', date '2026-07-10', array['XSX']),
    ('the-alters-last-variable', 'The Alters Last Variable', '13 de Julho', date '2026-07-13', array['PC','PS5','XSX']),
    ('hell-clock', 'Hell Clock', '14 de Julho', date '2026-07-14', array['PS5','XSX']),
    ('cozy-grove-camp-spirit', 'Cozy Grove Camp Spirit', '15 de Julho', date '2026-07-15', array['PC','SWITCH','SWITCH 2','PS5','PS4','XSX','XBOX ONE']),
    ('teeto', 'Teeto', '15 de Julho', date '2026-07-15', array['PC','SWITCH','SWITCH 2','PS5']),
    ('culdcept-begins', 'Culdcept Begins', '16 de Julho', date '2026-07-16', array['PC','SWITCH','SWITCH 2']),
    ('hell-maiden', 'Hell Maiden', '16 de Julho', date '2026-07-16', array['PC']),
    ('ebaseball-pro-spirit-2026', 'eBaseball Pro Spirit 2026', '16 de Julho', date '2026-07-16', array['PC','PS5']),
    ('the-guild-europe-1410', 'The Guild Europe 1410', '16 de Julho', date '2026-07-16', array['PC']),
    ('heave-ho-2', 'Heave Ho 2', '16 de Julho', date '2026-07-16', array['PC','SWITCH','SWITCH 2']),
    ('moss-the-forgotten-relic', 'Moss The Forgotten Relic', '16 de Julho', date '2026-07-16', array['PC','SWITCH','SWITCH 2','PS5','XSX']),
    ('dive-or-die-children-of-rain', 'Dive or Die: Children of Rain', '21 de Julho', date '2026-07-21', array['PC']),
    ('fading-echo', 'Fading Echo', '21 de Julho', date '2026-07-21', array['PC']),
    ('tears-of-metal', 'Tears of Metal', '22 de Julho', date '2026-07-22', array['PC']),
    ('dragonsword-awakening', 'DragonSword: Awakening', '23 de Julho', date '2026-07-23', array['PC']),
    ('cultic', 'Cultic', '23 de Julho', date '2026-07-23', array['SWITCH 2','PS5','XSX']),
    ('tormentum-ii', 'Tormentum II', '23 de Julho', date '2026-07-23', array['PC']),
    ('forever-skies', 'Forever Skies', '27 de Julho', date '2026-07-27', array['XSX']),
    ('go-north', 'Go North', '28 de Julho', date '2026-07-28', array['PC','XSX']),
    ('gothic-classic', 'Gothic Classic', '28 de Julho', date '2026-07-28', array['PS5','PS4','XSX','XBOX ONE']),
    ('bloodrayne-definitive-collection', 'BloodRayne Definitive Collection', '29 de Julho', date '2026-07-29', array['SWITCH']),
    ('exstetra-hd-remastered', 'Exstetra HD Remastered', '29 de Julho', date '2026-07-29', array['PC']),
    ('aretha-collection-1993-1995', 'Aretha Collection 1993-1995', '30 de Julho', date '2026-07-30', array['SWITCH','PS5','PS4']),
    ('blue-reflection-quartet', 'Blue Reflection Quartet', '30 de Julho', date '2026-07-30', array['PC','SWITCH','SWITCH 2','PS5']),
    ('exstetra', 'Exstetra', '30 de Julho', date '2026-07-30', array['PC']),
    ('xenoblade-chronicles-2-switch-2-edition', 'Xenoblade Chronicles 2 Nintendo Switch 2 Edition', '30 de Julho', date '2026-07-30', array['SWITCH 2'])
)
insert into public.release_radar_items
  (id, game, release_label, release_date, schedule_label, platforms, image_url, badge, category, sort_order)
select
  id,
  game,
  release_label,
  release_date,
  'Data confirmada',
  platforms,
  null,
  'Lançamento',
  'upcoming',
  3000 + row_number() over (order by release_date, game) * 10
from catalog
on conflict (id) do nothing;

with catalog(id, game, release_label, platforms) as (
  values
    ('persona-6', 'Persona 6', 'Em 2027', array[]::text[]),
    ('cassette-beasts-2002', 'Cassette Beasts 2002', 'A ser anunciada', array[]::text[]),
    ('crazy-taxi-world-tour', 'Crazy Taxi: World Tour', 'Em breve', array['PS5','XSX','SWITCH 2','PC']),
    ('resident-evil-veronica', 'Resident Evil Veronica', 'Em 2027', array['PS5','XSX','SWITCH 2','PC']),
    ('final-fantasy-vii-revelation', 'Final Fantasy VII Revelation', 'Em breve', array['PS5','XSX','SWITCH 2','PC']),
    ('virtua-fighter-crossroads', 'Virtua Fighter Crossroads', 'Em breve', array[]::text[]),
    ('ill', 'ILL', 'Em 2027', array['PS5','XSX','PC']),
    ('stuntman-hollywood', 'Stuntman Hollywood', 'A ser anunciada', array[]::text[]),
    ('until-dawn-2', 'Until Dawn 2', 'Em 2027', array['PS5']),
    ('god-of-war-laufey', 'God of War Laufey', 'Em breve', array[]::text[]),
    ('drowned-lake', 'Drowned Lake', 'A ser anunciada', array[]::text[]),
    ('fatekeeper', 'Fatekeeper', 'Acesso antecipado', array['PC']),
    ('dragon-quest-xii-beyond-dreams', 'Dragon Quest XII: Beyond Dreams', 'A ser anunciado', array[]::text[])
)
insert into public.release_radar_items
  (id, game, release_label, release_date, schedule_label, platforms, image_url, badge, category, sort_order)
select
  id,
  game,
  release_label,
  null,
  'A confirmar',
  platforms,
  null,
  'A confirmar',
  'upcoming',
  5000 + row_number() over (order by game) * 10
from catalog
on conflict (id) do nothing;
