create table if not exists public.home_engagement_events (
  id bigint generated by default as identity primary key,
  event_name text not null check (event_name in ('article', 'brickboard', 'radar', 'return_summary')),
  target text check (target is null or char_length(target) <= 180),
  created_at timestamptz not null default now()
);

create index if not exists home_engagement_events_created_at_idx
  on public.home_engagement_events (created_at desc);

alter table public.home_engagement_events enable row level security;

drop policy if exists home_engagement_events_public_insert on public.home_engagement_events;
create policy home_engagement_events_public_insert on public.home_engagement_events
  for insert to anon, authenticated
  with check (
    event_name in ('article', 'brickboard', 'radar', 'return_summary')
    and (target is null or char_length(target) <= 180)
  );

drop policy if exists home_engagement_events_admin_read on public.home_engagement_events;
create policy home_engagement_events_admin_read on public.home_engagement_events
  for select to authenticated
  using (coalesce((select auth.jwt() -> 'app_metadata' ->> 'is_admin')::boolean, false));

grant insert on public.home_engagement_events to anon, authenticated;
grant select on public.home_engagement_events to authenticated;
grant usage, select on sequence public.home_engagement_events_id_seq to anon, authenticated;
