insert into public.release_radar_items
  (id, game, release_label, schedule_label, platforms, image_url, badge, category, post_slug, sort_order, is_active, release_date)
values
  ('the-sinking-city-2', 'The Sinking City 2', '18 de Agosto', 'Terça-feira', array['PC','PS5','XSX'], null, 'Terror', 'upcoming', null, 20260818, false, date '2026-08-18'),
  ('metal-gear-solid-master-collection-vol-2', 'Metal Gear Solid: Master Collection Vol. 2', '27 de Agosto', 'Quinta-feira', array['PC','PS5','XSX','SWITCH','SWITCH 2'], null, 'Coleção', 'upcoming', null, 20260827, false, date '2026-08-27'),
  ('star-wars-zero-company', 'Star Wars: Zero Company', '27 de Agosto', 'Quinta-feira', array['PC','PS5','XSX'], null, 'Estratégia', 'upcoming', null, 20260828, false, date '2026-08-27'),
  ('elden-ring-tarnished-edition', 'Elden Ring: Tarnished Edition', '28 de Agosto', 'Sexta-feira', array['SWITCH 2'], null, 'RPG de ação', 'upcoming', null, 20260829, false, date '2026-08-28'),
  ('the-blood-of-the-dawnwalker', 'The Blood of the Dawnwalker', '3 de Setembro', 'Quinta-feira', array['PC','PS5','XSX'], null, 'RPG de ação', 'upcoming', null, 20260903, false, date '2026-09-03'),
  ('onimusha-way-of-the-sword', 'Onimusha: Way of the Sword', '4 de Setembro', 'Sexta-feira', array['PC','PS5','XSX','SWITCH 2'], null, 'Ação', 'upcoming', null, 20260904, false, date '2026-09-04'),
  ('halloween-the-game', 'Halloween: The Game', '8 de Setembro', 'Terça-feira', array['PC','PS5','XSX'], null, 'Terror', 'upcoming', null, 20260908, false, date '2026-09-08'),
  ('fire-emblem-fortunes-weave', 'Fire Emblem: Fortune''s Weave', '17 de Setembro', 'Quinta-feira', array['SWITCH 2'], null, 'RPG tático', 'upcoming', null, 20260917, false, date '2026-09-17'),
  ('lego-batman-legacy-of-the-dark-knight', 'LEGO Batman: Legacy of the Dark Knight', '18 de Setembro', 'Sexta-feira', array['SWITCH 2'], null, 'Ação e aventura', 'upcoming', null, 20260918, false, date '2026-09-18'),
  ('dune-awakening-consoles', 'Dune: Awakening', '22 de Setembro', 'Terça-feira', array['PS5','XSX'], null, 'Sobrevivência', 'upcoming', null, 20260922, false, date '2026-09-22'),
  ('control-resonant', 'Control Resonant', '24 de Setembro', 'Quinta-feira', array['PC','PS5','XSX'], null, 'Ação', 'upcoming', null, 20260924, false, date '2026-09-24'),
  ('silent-hill-townfall', 'Silent Hill: Townfall', '24 de Setembro', 'Quinta-feira', array['PC','PS5'], null, 'Terror', 'upcoming', null, 20260925, false, date '2026-09-24'),
  ('ea-sports-fc-27', 'EA Sports FC 27', '25 de Setembro', 'Sexta-feira', array['PC','PS5','PS4','XSX','XBOX ONE','SWITCH','SWITCH 2'], null, 'Esporte', 'upcoming', null, 20260926, false, date '2026-09-25'),
  ('ace-combat-8-wings-of-theve', 'Ace Combat 8: Wings of Theve', '28 de Setembro', 'Segunda-feira', array['PC','PS5','XSX'], null, 'Combate aéreo', 'upcoming', null, 20260928, false, date '2026-09-28'),
  ('minecraft-dungeons-2', 'Minecraft Dungeons 2', '29 de Setembro', 'Terça-feira', array['PC','PS5','XSX','SWITCH 2'], null, 'Ação e aventura', 'upcoming', null, 20260929, false, date '2026-09-29'),
  ('dynasty-warriors-3-remastered', 'Dynasty Warriors 3: Complete Edition Remastered', '1 de Outubro', 'Quinta-feira', array['PC','PS5','XSX','SWITCH','SWITCH 2'], null, 'Ação', 'upcoming', null, 20261001, false, date '2026-10-01'),
  ('rayman-legends-retold', 'Rayman Legends Retold', '1 de Outubro', 'Quinta-feira', array['PC','PS5','XSX','SWITCH 2'], null, 'Plataforma', 'upcoming', null, 20261002, false, date '2026-10-01'),
  ('star-wars-galactic-racer', 'Star Wars: Galactic Racer', '6 de Outubro', 'Terça-feira', array['PC','PS5','XSX'], null, 'Corrida', 'upcoming', null, 20261006, false, date '2026-10-06'),
  ('kingdom-hearts-collection-2026', 'Kingdom Hearts Collection', '8 de Outubro', 'Quinta-feira', array['PC','PS5','XSX','SWITCH 2'], null, 'RPG de ação', 'upcoming', null, 20261008, false, date '2026-10-08'),
  ('dragons-dogma-2-dark-arisen', 'Dragon''s Dogma 2: Dark Arisen', '9 de Outubro', 'Sexta-feira', array['PC','PS5','XSX','SWITCH 2'], null, 'RPG de ação', 'upcoming', null, 20261009, false, date '2026-10-09'),
  ('valor-mortis', 'Valor Mortis', '13 de Outubro', 'Terça-feira', array['PC','PS5','XSX'], null, 'Ação', 'upcoming', null, 20261013, false, date '2026-10-13'),
  ('castlevania-belmonts-curse', 'Castlevania: Belmont''s Curse', '15 de Outubro', 'Quinta-feira', array['PC','PS5','XSX'], null, 'Ação', 'upcoming', null, 20261015, false, date '2026-10-15'),
  ('final-fantasy-resonance', 'Final Fantasy Resonance', '22 de Outubro', 'Quinta-feira', array['PC','PS5','XSX','SWITCH','SWITCH 2'], null, 'RPG', 'upcoming', null, 20261022, false, date '2026-10-22'),
  ('nintendo-switch-sports-resort', 'Nintendo Switch Sports Resort', '22 de Outubro', 'Quinta-feira', array['SWITCH 2'], null, 'Esporte', 'upcoming', null, 20261023, false, date '2026-10-22'),
  ('metaphor-refantazio-switch-2', 'Metaphor: ReFantazio', '12 de Novembro', 'Quinta-feira', array['SWITCH 2'], null, 'RPG', 'upcoming', null, 20261112, false, date '2026-11-12'),
  ('dragon-quest-monsters-the-withered-world', 'Dragon Quest Monsters: The Withered World', '3 de Dezembro', 'Quinta-feira', array['PC','PS5','XSX','SWITCH','SWITCH 2'], null, 'RPG', 'upcoming', null, 20261203, false, date '2026-12-03'),
  ('xenoblade-chronicles-3-switch-2', 'Xenoblade Chronicles 3: Nintendo Switch 2 Edition', '3 de Dezembro', 'Quinta-feira', array['SWITCH 2'], null, 'RPG', 'upcoming', null, 20261204, false, date '2026-12-03'),
  ('stranger-than-heaven', 'STRANGER THAN HEAVEN', '15 de Janeiro', 'Sexta-feira', array['PC','PS5','XSX'], null, 'Ação e aventura', 'upcoming', null, 20270115, false, date '2027-01-15'),
  ('tomb-raider-legacy-of-atlantis', 'Tomb Raider: Legacy of Atlantis', '12 de Fevereiro', 'Sexta-feira', array['PC','PS5','XSX','SWITCH 2'], null, 'Ação e aventura', 'upcoming', null, 20270212, false, date '2027-02-12'),
  ('persona-4-revival', 'Persona 4 Revival', '18 de Fevereiro', 'Quinta-feira', array['PC','PS5','XSX'], null, 'RPG', 'upcoming', null, 20270218, false, date '2027-02-18'),
  ('fable-2027', 'Fable', '23 de Fevereiro', 'Terça-feira', array['PC','PS5','XSX'], null, 'RPG de ação', 'upcoming', null, 20270223, false, date '2027-02-23'),
  ('metro-2039', 'METRO 2039', 'Fevereiro de 2027', 'Data ainda não anunciada', array['PC','PS5','XSX'], null, 'Tiro e sobrevivência', 'upcoming', null, 20270299, false, null)
on conflict (id) do update
set
  game = excluded.game,
  release_label = excluded.release_label,
  schedule_label = excluded.schedule_label,
  platforms = excluded.platforms,
  badge = excluded.badge,
  category = excluded.category,
  sort_order = excluded.sort_order,
  release_date = excluded.release_date,
  updated_at = now();
